<a href="https://colab.research.google.com/github/pri2k/Insurance-Purchase-Prediction/blob/main/Neural_Network_Gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
df = pd.read_csv('insurance_data.csv')
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2, random_state=25)

In [ ]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100


### **Model**

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(1,input_shape = (2,) , activation = 'sigmoid', kernel_initializer = 'ones', bias_initializer = 'zeros')
])

model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

model.fit(X_train_scaled, y_train, epochs = 20000)

Streaming output truncated to the last 5000 lines.
Epoch 17501/20000
1/1 [==============================] - 0s 15ms/step - loss: 0.4103 - accuracy: 0.8636
Epoch 17502/20000
1/1 [==============================] - 0s 15ms/step - loss: 0.4103 - accuracy: 0.8636
Epoch 17503/20000
1/1 [==============================] - 0s 12ms/step - loss: 0.4103 - accuracy: 0.8636
Epoch 17504/20000
1/1 [==============================] - 0s 11ms/step - loss: 0.4103 - accuracy: 0.8636
Epoch 17505/20000
1/1 [==============================] - 0s 16ms/step - loss: 0.4103 - accuracy: 0.8636
Epoch 17506/20000
1/1 [==============================] - 0s 13ms/step - loss: 0.4103 - accuracy: 0.8636
Epoch 17507/20000
1/1 [==============================] - 0s 17ms/step - loss: 0.4103 - accuracy: 0.8636
Epoch 17508/20000
1/1 [==============================] - 0s 10ms/step - loss: 0.4103 - accuracy: 0.8636
Epoch 17509/20000
1/1 [==============================] - 0s 10ms/step - loss: 0.4103 - accuracy: 0.8636
Epoch 17510/2

### **Evaluate**

In [ ]:
model.evaluate(X_test_scaled,y_test)

1/1 [==============================] - 0s 209ms/step - loss: 0.3550 - accuracy: 1.0000


[0.3549776077270508, 1.0]

In [ ]:
model.predict(X_test_scaled)

1/1 [==============================] - 0s 68ms/step


array([[0.7054848 ],
       [0.3556957 ],
       [0.16827832],
       [0.47801185],
       [0.7260696 ],
       [0.8294983 ]], dtype=float32)

In [ ]:
# lets compare

y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

Success

---



In [ ]:
coef, intercept = model.get_weights()
coef, intercept

(array([[5.060863 ],
        [1.4086521]], dtype=float32),
 array([-2.913703], dtype=float32))

### **Functions**

In [ ]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

print(sigmoid(1))
print(sigmoid(0))
print(sigmoid(-1))
print(sigmoid(10))
print(sigmoid(100))
print(sigmoid(-100))
print(sigmoid(50))

0.7310585786300049
0.5
0.2689414213699951
0.9999546021312976
1.0
3.7200759760208356e-44
1.0


In [ ]:
def predict_function(age, affordibility, w1, w2, b):
  weight = w1*age + w2*affordibility + b
  return sigmoid(weight)


In [ ]:
def log_loss(y_true, y_predicted):
  epsilon = 1e-25
  y_predicted_new = np.clip(y_predicted,epsilon,1-epsilon)
  return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [ ]:
def gradient_descent(age, affordability, y_train, epochs):
  w1 = w2 = 1
  b = 0
  rate = 0.001
  n = len(age)
  for i in range(epochs):
    weight = w1*age + w2*affordability + b
    y_preds = sigmoid(weight)
    loss = log_loss(y_train, y_preds)
    w1_d = (1/n)* np.dot(np.transpose(age),y_preds-y_train)
    w2_d = (1/n)* np.dot(np.transpose(affordability),y_preds-y_train)
    w1 = w1 - rate*w1_d
    w2 = w2 - rate*w2_d
    b = b - rate*np.mean(y_preds-y_train)
    if i%1000 == 0:
      print(f'Epoch:{i}, w1:{w1}, w2:{w2}, b:{b}, loss:{loss}')
  return w1, w2, b

w1, w2, b = gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,20000)

Epoch:0, w1:0.9999498152669404, w2:0.999896696250789, b:-0.00022683735472737166, loss:0.7113403233723417
Epoch:1000, w1:0.9604178280832437, w2:0.9134496488657603, b:-0.20027372153880685, loss:0.6619125508766145
Epoch:2000, w1:0.939614987253973, w2:0.857160001479101, b:-0.3534264192541708, loss:0.6346145463290856
Epoch:3000, w1:0.9333535274305056, w2:0.8245954843148237, b:-0.47029517647938074, loss:0.6197211701552862
Epoch:4000, w1:0.9377714943634405, w2:0.809421185034082, b:-0.5604907520345471, loss:0.6112662449346995
Epoch:5000, w1:0.9497757593973367, w2:0.8064096471093234, b:-0.631634773653002, loss:0.6060172316931477
Epoch:6000, w1:0.967066968140226, w2:0.8116196952223678, b:-0.6893603159847768, loss:0.6023424004345131
Epoch:7000, w1:0.9880034932988015, w2:0.8222223454642104, b:-0.7376758692207017, loss:0.5994494543573664
Epoch:8000, w1:1.0114389666338455, w2:0.836243504059775, b:-0.7793760951813566, loss:0.5969610301426158
Epoch:9000, w1:1.036582524939249, w2:0.8523296157605607, b:

In [ ]:
print("my models weights", w1, w2, b)
print(model.get_weights())

print()
print("My Predictions")
print(predict_function(X_test_scaled['age'],X_test_scaled['affordibility'],w1,w2,b))
print()
print("Actual Predictions")
print(model.predict(X_test_scaled))
print()
print(y_test)

my models weights 8.267810355161846 1.633041726875239 -4.424803667048713
[array([[5.060863 ],
       [1.4086521]], dtype=float32), array([-2.913703], dtype=float32)]

My Predictions
2     0.749155
10    0.213567
21    0.093200
11    0.383014
14    0.778934
9     0.904789
dtype: float64

Actual Predictions
1/1 [==============================] - 0s 19ms/step
[[0.7054848 ]
 [0.3556957 ]
 [0.16827832]
 [0.47801185]
 [0.7260696 ]
 [0.8294983 ]]

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64
